language: python
python:
  - 3.6
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

before_install:
- sudo apt-get install -y pandoc

install:
  # Install the packages listed in requirements.txt.
  - pip install -r requirements.txt

env:
   global:
     # Doctr deploy key for PAHdb/cookbook
     - secure: "roOwObpnIEkMnOcg4POlBC7dBwzKU6cwlFlCTwp+z9Lwih1uOU64tXgzlvSG1TneAstMg781ufI07lQIY/8PHtzvFyxXm1qvx/iWaehe/H9QIv8qcVrKXd6UoKkcpNOQMK6d/lIbnErEKwUI7NTV+OeV+VYQ6mrzXoNkihxkCblAyjnut/+XP3OuWWxIUAto1pwVrQ9y1plsOaybyRhuQI5/N7SfDVsGigQGtWr072+LCKpSuCoSwJSTp2jnSd4dSBNj745wdYP5Y41UBt22OjMOBQfyyo0FomFJh+jJrF9b43oo62icIx0aHVDJu72ctZn/9rBaLR2M7r5QlxTYhtj8MZdPtr5BjzrlCnHpBgbrL1z3B5l1vGnd+8gTY3W89UWlxvs5rZM9qS9fmQOGbZA4dp3yv4q7HDBxtTRyLjBcMVJsVkK4sK7EhByAvwKzvIILdCNhYU9mS3/SWAxY+pXNqa1+pq/cZFKgbImcEzC6L9AV5NeOaM7WdW2GY9vkHe2wBlc1SuoHzhoBKtO9wwqb7LUrEXUEWt4I1txzebssGXXU2LO4iPRkkSB1t3dDwJsGzofaT5r6yMd0TjWjgGP/eBXe596VtJOcAvqWSOqdk88WL6Rv/klQnP05GC2aNFQUg9GaSZfCrZJLIIGMWKGlDeMsFRwhA+AVQJRrvtY="

script:
  - make html  # Build the documentation.
  - set -e
  - doctr deploy --built-docs _build/html .  # Publish the documentation.